version: '3.9'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 9000:80
    depends_on:
      - db
    networks:
      - mynetwork

  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - 1433:1433
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Pass44w0rd
      - MSSQL_TCP_ENABLED=1
      - MSSQL_TCP_PORT=1433
      - MSSQLNP_ENABLED=1
    volumes:
      - dbdata:/var/opt/mssql
    networks:
      - mynetwork

networks:
  mynetwork:

volumes:
  dbdata:
